function grid = mit_oceanmasks(varargin)
% function grid = mit_oceanmasks(grid)
% create masks for the individual oceans
% hfacc/s/w have to be available for this
% 
% This is the new way using 1 degree WOA13 basin masks from https://www.nodc.noaa.gov/OC5/woa13/masks13.html
%  rather than having to manually enter boundaries for each configuration
%
% The mask is the Basin_0m field, numbered as follows:
% 1 Atlantic Ocean 
% 2 Pacific Ocean 
% 3 Indian Ocean 
% 4 Mediterranean Sea 
% 5 Baltic Sea 
% 6 Black Sea
% 7 Red Sea
% 8 Persian Gulf
% 9 Hudson Bay
% 10 Southern Ocean
% 11 Arctic Ocean
% 12 Sea of Japan
% 53 Caspian Sea
% 56 Bay of Bengal
% 
% jml1@mit.edu 01/08/2017
switch nargin
    case 1
        grid=varargin{1};
        plotit=0;
    case 2
        grid=varargin{1};
        plotit=varargin{2};
    otherwise
        error('Too many input arguments')
end

% Read in field
[Latitude,Longitude,WOAMask] = importfile('woa13_basinmask_01.msk');

% Find out if the grid has been rotated and rotate so range is the same as input grid
if (min(Longitude)<0) ~= (min(grid.xc(:))<0)
    Longitude(Longitude<0)=Longitude(Longitude<0)+360;
end

% Create interpolation object
Fbasin=scatteredInterpolant(Longitude,Latitude,WOAMask,'nearest','nearest');

if isfield(grid,'xc') && isfield(grid,'cmask') && isfield(grid,'hfacc')
    % Interpolate onto model grid
    cmask=repmat(Fbasin(grid.xc,grid.yc),[1,1,size(grid.cmask,3)]);
    
    grid.so_hfacc       = grid.hfacc; grid.so_hfacc      (cmask~=10)=NaN;
    grid.arctic_hfacc   = grid.hfacc; grid.arctic_hfacc  (cmask~=11)=NaN;
    
    % Replace the Southern Ocean value of 10 with (one of) the last rows to
    % seperate into Atlantic, Pacific and Indian sectors
    cmask(:,1:length(find(unique(grid.yc)<=-45)),:)=repmat(cmask(:,find(unique(grid.yc)<=-45,1,'last')),[1,length(find(unique(grid.yc)<=-45)),size(grid.hfacc,3)]);
    
    grid.atlantic_hfacc = grid.hfacc; grid.atlantic_hfacc(cmask~=1 )=NaN;
    grid.pacific_hfacc  = grid.hfacc; grid.pacific_hfacc (cmask~=2 & cmask~=12)=NaN;
    grid.indic_hfacc    = grid.hfacc; grid.indic_hfacc   (cmask~=3 & cmask~=56)=NaN;
end

if isfield(grid,'xg') && isfield(grid,'umask') && isfield(grid,'hfacw')
    umask=repmat(Fbasin(grid.xg,grid.yc),[1,1,size(grid.umask,3)]);
    
    grid.so_hfacw       = grid.hfacw; grid.so_hfacw      (umask~=10)=NaN;
    grid.arctic_hfacw   = grid.hfacw; grid.arctic_hfacw  (umask~=11)=NaN;
    
    % Replace the Southern Ocean value of 10 with (one of) the last rows to
    % seperate into Atlantic, Pacific and Indian sectors
    umask(:,1:length(find(unique(grid.yc)<=-45)),:)=repmat(umask(:,find(unique(grid.yc)<=-45,1,'last')),[1,length(find(unique(grid.yc)<=-45)),size(grid.hfacw,3)]);
    
    grid.atlantic_hfacw = grid.hfacw; grid.atlantic_hfacw(umask~=1 )=NaN;
    grid.pacific_hfacw  = grid.hfacw; grid.pacific_hfacw (umask~=2 & umask~=12)=NaN;
    grid.indic_hfacw    = grid.hfacw; grid.indic_hfacw   (umask~=3 & umask~=56)=NaN;
end

if isfield(grid,'yg') && isfield(grid,'vmask') && isfield(grid,'hfacs')
    vmask=repmat(Fbasin(grid.xc,grid.yg),[1,1,size(grid.vmask,3)]);
    
    grid.so_hfacs       = grid.hfacs; grid.so_hfacs      (umask~=10)=NaN;
    grid.arctic_hfacs   = grid.hfacs; grid.arctic_hfacs  (umask~=11)=NaN;
    
    % Replace the Southern Ocean value of 10 with (one of) the last rows to
    % seperate into Atlantic, Pacific and Indian sectors
    vmask(:,1:length(find(unique(grid.yg)<=-45)),:)=repmat(vmask(:,find(unique(grid.yg)<=-45,1,'last')),[1,length(find(unique(grid.yg)<=-45)),size(grid.hfacs,3)]);
    
    grid.atlantic_hfacs = grid.hfacs; grid.atlantic_hfacs(vmask~=1 )=NaN;
    grid.pacific_hfacs  = grid.hfacs; grid.pacific_hfacs (vmask~=2 & vmask~=12)=NaN;
    grid.indic_hfacs    = grid.hfacs; grid.indic_hfacs   (vmask~=3 & vmask~=56)=NaN;
end

if plotit==1;
    figure;
    spy(isnan(grid.hfacc(:,:,1)'),'kx'); axis xy
    hold on; 
    spy(~isnan(grid.atlantic_hfacc(:,:,1)'),'b.'); 
    spy(~isnan(grid.pacific_hfacc(:,:,1)'),'r.');
    spy(~isnan(grid.indic_hfacc(:,:,1)'),'g.'); 
    spy(~isnan(grid.arctic_hfacc(:,:,1)'),'m.'); 
    axis xy
    title('hfacc');
end

% Additional function to import WOA13 basin mask.
function [Latitude1,Longitude1,Basin_0m] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [LATITUDE1,LONGITUDE1,BASIN_0M] = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   [LATITUDE1,LONGITUDE1,BASIN_0M] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [Latitude1,Longitude1,Basin_0m] = importfile('basinmask_04.msk',3,
%   677826);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/08/02 12:46:11

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Latitude1 = dataArray{:, 1};
Longitude1 = dataArray{:, 2};
Basin_0m = dataArray{:, 3};

return

%% Old arbitrary way that required a new section for each configuration
%   if grid.nx == 128 && grid.ny == 64 
%   % masks for the zonal velocities:
%   % hfacw
%   
%   % Atlantic mask
%   grid.atlantic_hfacw = grid.hfacw;
%   ixsow = 9:104; % Southern and south Indian
%   iysow = 1:36;
%   grid.atlantic_hfacw(ixsow,iysow,:) = NaN;
%   ixnpw = 1:99; % North Pacific
%   iynpw = 36:50;
%   grid.atlantic_hfacw(ixnpw,iynpw,:) = NaN;
%   ixnnp = 40:85; % The very northern north Pacific
%   iynnp = 50:60;
%   grid.atlantic_hfacw(ixnnp,iynnp,:) = NaN;
%   
%   % Pacific mask
%   grid.pacific_hfacw = grid.hfacw;
%   ixaw = 104:128; % most of the atlantic
%   iyaw = 1:64;
%   grid.pacific_hfacw(ixaw,iyaw,:) = NaN;
%   ixnaw = 99:104; % baffin bay and gulf of Mexico
%   iynaw = 36:64;
%   grid.pacific_hfacw(ixnaw,iynaw,:) = NaN;
%   ixiw = 1:41; % most of the indic
%   iyiw = 1:64;
%   grid.pacific_hfacw(ixiw,iyiw,:) = NaN;
%   ixauw = 41:55;% water south and west of Australia
%   iyauw = 1:25;
%   grid.pacific_hfacw(ixauw,iyauw,:) = NaN;
%   
%   % masks for the meridional overturning stream functions:
%   % hfacs
%   
%   % Atlantic mask
%   grid.atlantic_hfacs = grid.hfacs;
%   ixso = 9:104; % Southern and south Indian
%   iyso = 1:36;
%   grid.atlantic_hfacs(ixso,iyso,:) = NaN;
%   ixnp = 1:97; % North Pacific
%   iynp = 36:50;
%   grid.atlantic_hfacs(ixnp,iynp,:) = NaN;
%   ixnnp = 40:85; % The very northern north Pacific
%   iynnp = 50:60;
%   grid.atlantic_hfacs(ixnnp,iynnp,:) = NaN;
%   ixsoc = 1:128; % complete southern ocean
%   iysoc = 1:20; % south of latg(12) = -34 degN;
%   grid.atlantic_hfacs(ixsoc,iysoc,:) = NaN;
%   
%   % Pacific mask
%   grid.pacific_hfacs = grid.hfacs;
%   ixa = 104:128; % most of the atlantic
%   iya = 1:64;
%   grid.pacific_hfacs(ixa,iya,:) = NaN;
%   ixna = 99:104; % baffin bay and gulf of Mexico
%   iyna = 36:64;
%   grid.pacific_hfacs(ixna,iyna,:) = NaN;
%   ixna2 = 98:100;
%   iyna2 = 40:42;
%   grid.pacific_hfacs(ixna2,iyna2,:) = NaN;
%   ixi = 1:41; % most of the indic
%   iyi = 1:64;
%   grid.pacific_hfacs(ixi,iyi,:) = NaN;
%   ixau = 41:55;% water south and west of Australia
%   iyau = 1:25;
%   grid.pacific_hfacs(ixau,iyau,:) = NaN;
% 
%   % Indian ocean
%   grid.indic_hfacs = grid.hfacs;
%   ixsoi = 1:128; % southern ocean
%   iysoi = 1:20;
%   grid.indic_hfacs(ixsoi,iysoi,:) = NaN;
%   ixap = [1:10 46:128]; % atlantic and pacific
%   iyap = 1:64;  
%   grid.indic_hfacs(ixap,iyap,:) = NaN;
%   iynps = 55:64; % north polar sea
%   grid.indic_hfacs(:,iynps,:) = NaN;
%   ixscs = 39:46; % south china sea
%   iyscs = 31:45;
%   grid.indic_hfacs(ixscs,iyscs,:) = NaN;
% 
%   % Southern Ocean
%   grid.so_hfacs = grid.hfacs;
%   % Mask everything above 36Deg S
%   iysom = 20:64;
%   grid.so_hfacs(:,iysom,:) = NaN;
% 
%   if exist('plotit','var')
%     figure;
%     spy(isnan(grid.hfacs(:,:,1)'),'kx');
%     hold on; 
%     spy(~isnan(grid.atlantic_hfacs(:,:,1)')); 
%     spy(~isnan(grid.indic_hfacs(:,:,1)'),'g.'); 
%     spy(~isnan(grid.so_hfacs(:,:,1)'),'r.'); 
%     spy(~isnan(grid.pacific_hfacs(:,:,1)'),'y.');
%     title('hfacs')
%     axis xy
%   end
%   
%   % masks for zonal averages of C-properties:
%   % hfacc
%   
%   % Atlantic mask
%   grid.atlantic_hfacc = grid.hfacc;
%   ixso = 10:104; % Southern and south Indian
%   iyso = 1:36;
%   grid.atlantic_hfacc(ixso,iyso,:) = NaN;
%   ixnp = 1:97; % North Pacific
%   iynp = 36:50;
%   grid.atlantic_hfacc(ixnp,iynp,:) = NaN;
%   ixnnp = 40:85; % The very northern north Pacific
%   iynnp = 50:60;
%   grid.atlantic_hfacc(ixnnp,iynnp,:) = NaN;
% %   ixsoc = 1:128; % complete southern ocean
% %   iysoc = 1:20; % south of latg(12) = -34 degN;
% %   grid.atlantic_hfacc(ixsoc,iysoc,:) = NaN;
%   
%   % Pacific mask
%   grid.pacific_hfacc = grid.hfacc;
%   ixa = 105:128; % most of the atlantic
%   iya = 1:64;
%   grid.pacific_hfacc(ixa,iya,:) = NaN;
%   ixna = 98:104; % baffin bay and gulf of Mexico
%   iyna = 36:64;
%   grid.pacific_hfacc(ixna,iyna,:) = NaN;
%   ixna2 = 98:100;
%   iyna2 = 40:42;
%   grid.pacific_hfacc(ixna2,iyna2,:) = NaN;
%   ixi = 1:41; % most of the indic
%   iyi = 1:64;
%   grid.pacific_hfacc(ixi,iyi,:) = NaN;
% %   ixau = 41:55;% water south and west of Australia
% %   iyau = 1:25;
% %   grid.pacific_hfacc(ixau,iyau,:) = NaN;
%   grid.pacific_hfacc(42:45,1:30)=NaN;
%   
%   % Indian ocean
%   grid.indic_hfacc =grid.hfacc;
% %   ixsoi = 1:128; % southern ocean
% %   iysoi = 1:20;
% %   grid.indic_hfacc(ixsoi,iysoi,:) = NaN;
%   ixap = [1:9 46:128]; % atlantic and pacific
%   iyap = 1:64;  
%   grid.indic_hfacc(ixap,iyap,:) = NaN;
%   iynps = 55:64; % north polar sea
%   grid.indic_hfacc(:,iynps,:) = NaN;
%   ixscs = 39:46; % south china sea
%   iyscs = 31:45;
%   grid.indic_hfacc(ixscs,iyscs,:) = NaN;
%   
%   if exist('plotit','var')
%     figure;
%     spy(isnan(grid.hfacc(:,:,1)'),'kx'); axis xy
%     hold on; 
%     spy(~isnan(grid.atlantic_hfacc(:,:,1)')); 
%     spy(~isnan(grid.pacific_hfacc(:,:,1)'),'r.');
%     spy(~isnan(grid.indic_hfacc(:,:,1)'),'g.'); 
%     axis xy
%     title('hfacc');
% 
%   end
%   elseif grid.nx == 360 && grid.ny >= 160
%       % masks for the zonal velocities:
%   % hfacw
%   
%   % Atlantic mask
%   grid.atlantic_hfacw = grid.hfacw;
%   ixsow = 22:292; % Southern and south Indian
%   iysow = 1:89;
%   grid.atlantic_hfacw(ixsow,iysow,:) = NaN;
%   ixnpw = 1:263; % North Pacific
%   iynpw = 89:132;
%   grid.atlantic_hfacw(ixnpw,iynpw,:) = NaN;
%   ixnnp = 100:250; % The very northern north Pacific
%   iynnp = 132:160;
%   grid.atlantic_hfacw(ixnnp,iynnp,:) = NaN;
%   ixeqp = 263:278; % The Eastern equatorial Pacific
%   iyeqp = 89:97;
%   grid.atlantic_hfacw(ixeqp,iyeqp,:) = NaN;
%   
%   % Pacific mask
%   grid.pacific_hfacw = grid.hfacw;
%   ixaw = 292:360; % most of the atlantic
%   iyaw = 1:160;
%   grid.pacific_hfacw(ixaw,iyaw,:) = NaN;
%   ixnaw = 262:292; % baffin bay and gulf of Mexico
%   iynaw = 97:160;
%   grid.pacific_hfacw(ixnaw,iynaw,:) = NaN;
%   ixsgm = 278:292; % south gulf of Mexico
%   iysgm = 90:97;
%   grid.pacific_hfacw(ixsgm,iysgm,:) = NaN;
%   ixiw = 1:101; % most of the indic
%   iyiw = 1:160;
%   grid.pacific_hfacw(ixiw,iyiw,:) = NaN;
%   ixauw = 101:146;% water south and west of Australia
%   iyauw = 1:80;
%   grid.pacific_hfacw(ixauw,iyauw,:) = NaN;
%   
%   
%   % masks for the meridional overturning stream functions:
%   % hfacs
%   
%   % Atlantic mask
%   grid.atlantic_hfacs = grid.hfacs;
%   ixsow = 22:292; % Southern and south Indian
%   iysow = 1:89;
%   grid.atlantic_hfacs(ixsow,iysow,:) = NaN;
%   ixnpw = 1:263; % North Pacific
%   iynpw = 89:132;
%   grid.atlantic_hfacs(ixnpw,iynpw,:) = NaN;
%   ixnnp = 100:250; % The very northern north Pacific
%   iynnp = 132:160;
%   grid.atlantic_hfacs(ixnnp,iynnp,:) = NaN;
%   ixeqp = 263:278; % The Eastern equatorial Pacific
%   iyeqp = 89:97;
%   grid.atlantic_hfacs(ixeqp,iyeqp,:) = NaN;
%   
%   % Pacific mask
%   grid.pacific_hfacs = grid.hfacs;
%   ixaw = 292:360; % most of the atlantic
%   iyaw = 1:160;
%   grid.pacific_hfacs(ixaw,iyaw,:) = NaN;
%   ixnaw = 262:292; % baffin bay and gulf of Mexico
%   iynaw = 97:160;
%   grid.pacific_hfacs(ixnaw,iynaw,:) = NaN;
%   ixsgm = 278:292; % south gulf of Mexico
%   iysgm = 90:97;
%   grid.pacific_hfacs(ixsgm,iysgm,:) = NaN;
%   ixiw = 1:101; % most of the indic
%   iyiw = 1:160;
%   grid.pacific_hfacs(ixiw,iyiw,:) = NaN;
%   ixauw = 101:146;% water south and west of Australia
%   iyauw = 1:80;
%   grid.pacific_hfacs(ixauw,iyauw,:) = NaN;
% 
%   % Indian ocean
%   grid.indic_hfacs = grid.hfacs;
%   ixsoi = 1:360; % southern ocean
%   iysoi = 1:45;
%   grid.indic_hfacs(ixsoi,iysoi,:) = NaN;
%   ixap = [1:22 146:360]; % atlantic and pacific
%   iyap = 45:160;  
%   grid.indic_hfacs(ixap,iyap,:) = NaN;
%   ixwp = 101:146; % western pacific
%   iywp = 80:160;  
%   grid.indic_hfacs(ixwp,iywp,:) = NaN;
%   ixnps = 22:57; % north polar sea & med
%   iynps = 100:160; 
%   grid.indic_hfacs(ixnps,iynps,:) = NaN;
% 
%   % Southern Ocean
%   grid.so_hfacs = grid.hfacs;
%   % Mask everything above 36Deg S
%   iysom = 45:160;
%   grid.so_hfacs(:,iysom,:) = NaN;
% 
%   if exist('plotit','var')
%     figure;
%     spy(isnan(grid.hfacs(:,:,1)'),'kx');
%     hold on; 
%     spy(~isnan(grid.atlantic_hfacs(:,:,1)')); 
%     spy(~isnan(grid.indic_hfacs(:,:,1)'),'g.'); 
%     spy(~isnan(grid.so_hfacs(:,:,1)'),'r.'); 
%     spy(~isnan(grid.pacific_hfacs(:,:,1)'),'y.');
%     title('hfacs')
%     axis xy
%   end
%   
%   % masks for zonal averages of C-properties:
%   % hfacc
%   
%   % Atlantic mask
%   grid.atlantic_hfacc = grid.hfacc;
%   ixsow = 22:292; % Southern and south Indian
%   iysow = 1:89;
%   grid.atlantic_hfacc(ixsow,iysow,:) = NaN;
%   ixnpw = 1:263; % North Pacific
%   iynpw = 89:132;
%   grid.atlantic_hfacc(ixnpw,iynpw,:) = NaN;
%   ixnnp = 100:250; % The very northern north Pacific
%   iynnp = 132:160;
%   grid.atlantic_hfacc(ixnnp,iynnp,:) = NaN;
%   ixeqp = 263:278; % The Eastern equatorial Pacific
%   iyeqp = 89:97;
%   grid.atlantic_hfacc(ixeqp,iyeqp,:) = NaN;
%   
%   % Pacific mask
%   grid.pacific_hfacc = grid.hfacc;
%   ixaw = 292:360; % most of the atlantic
%   iyaw = 1:160;
%   grid.pacific_hfacc(ixaw,iyaw,:) = NaN;
%   ixnaw = 262:292; % baffin bay and gulf of Mexico
%   iynaw = 97:160;
%   grid.pacific_hfacc(ixnaw,iynaw,:) = NaN;
%   ixsgm = 278:292; % south gulf of Mexico
%   iysgm = 90:97;
%   grid.pacific_hfacc(ixsgm,iysgm,:) = NaN;
%   ixiw = 1:101; % most of the indic
%   iyiw = 1:160;
%   grid.pacific_hfacc(ixiw,iyiw,:) = NaN;
%   ixauw = 101:146;% water south and west of Australia
%   iyauw = 1:80;
%   grid.pacific_hfacc(ixauw,iyauw,:) = NaN;
% 
%   % Indian ocean
%   grid.indic_hfacc = grid.hfacc;
% %   ixsoi = 1:360; % southern ocean
% %   iysoi = 1:45;
% %   grid.indic_hfacc(ixsoi,iysoi,:) = NaN;
%   ixap = [1:22 146:360]; % atlantic and pacific
%   iyap = 1:160;  
%   grid.indic_hfacc(ixap,iyap,:) = NaN;
%   ixwp = 101:146; % western pacific
%   iywp = 80:160;  
%   grid.indic_hfacc(ixwp,iywp,:) = NaN;
%   ixnps = 22:57; % north polar sea & med
%   iynps = 100:160; 
%   grid.indic_hfacc(ixnps,iynps,:) = NaN;
% 
%   if exist('plotit','var')
%     figure;
%     spy(isnan(grid.hfacc(:,:,1)'),'kx'); axis xy
%     hold on; 
%     spy(~isnan(grid.atlantic_hfacc(:,:,1)')); 
%     spy(~isnan(grid.pacific_hfacc(:,:,1)'),'r.');
%     spy(~isnan(grid.indic_hfacc(:,:,1)'),'g.'); 
%     axis xy
%     title('hfacc');
%   end
%   else
%       error('Basin masks not setup for this configuration')
%   end
%  return
